// src/services/employee.service.ts
import prisma from "../prisma";

export const createEmployeeService = async (data: any) => {
  // The employeeId is auto-generated by Prisma (CUID)
  // Only the password is hashed before this point
  return prisma.employee.create({
    data,
  });
};

export const getEmployeesService = async () => {
  return prisma.employee.findMany({
    // Exclude sensitive fields
    select: {
      employeeId: true,
      fullName: true,
      emailAddress: true,
      assignedRole: true,
      assignedDepartment: true,
      appraisalState: true,
      baseSalary: true,
      allowances: true,
      deductions: true,
      isActive: true,
      joinedAt: true,
      username: true,
      teamId: true,
      managerId: true,
    }
  });
};

export const getEmployeeByIdService = async (id: bigint) => {
  return prisma.employee.findUnique({
    where: {
      employeeId: id,
    },
    select: {
      employeeId: true,
      fullName: true,
      emailAddress: true,
      assignedRole: true,
      assignedDepartment: true,
      appraisalState: true,
      baseSalary: true,
      allowances: true,
      deductions: true,
      isActive: true,
      joinedAt: true,
      username: true,
      last_login: true,
      teamId: true,
      managerId: true,
    }
  });
};

export const updateEmployeeService = async (
  id: bigint,
  data: any
) => {
  return prisma.employee.update({
    where: {
      employeeId: id,
    },
    data,
  });
};

export const deleteEmployeeService = async (id: bigint) => {
  return prisma.employee.delete({
    where: {
      employeeId: id,
    },
  });
};