// src/services/employee.service.ts
import prisma from "../prisma";

// Shape returned by the raw pg_trgm search query below. Columns are aliased
// back to their Prisma field names so serializeEmployee() in the controller
// can handle them exactly like any other employee row.
export interface EmployeeSearchRow {
  employeeId: string | bigint;
  fullName: string;
  emailAddress: string;
  assignedRole: string;
  assignedDepartment: string;
  appraisalState: string;
  baseSalary: unknown;
  allowances: unknown;
  deductions: unknown;
  isActive: boolean;
  joinedAt: string | bigint;
  username: string;
  teamId: string | null;
  managerId: string | bigint | null;
  similarity: number;
}

export const createEmployeeService = async (data: any) => {
  // The employeeId is auto-generated by Prisma (CUID)
  // Only the password is hashed before this point
  return prisma.employee.create({
    data,
  });
};

export const getEmployeesService = async () => {
  return prisma.employee.findMany({
    // Exclude sensitive fields
    select: {
      employeeId: true,
      fullName: true,
      emailAddress: true,
      assignedRole: true,
      assignedDepartment: true,
      appraisalState: true,
      baseSalary: true,
      allowances: true,
      deductions: true,
      isActive: true,
      joinedAt: true,
      username: true,
      teamId: true,
      managerId: true,
    }
  });
};

// ---------------------------------------------------------------------------
// Fuzzy/partial search powered by the pg_trgm Postgres extension
// (see prisma/migrations/20260821120000_add_employee_fullname_trgm_search).
//
// Matches on EITHER of two fields, so a single query box can find people
// by name OR by role:
//   - full_name ILIKE '%q%'        -> plain substring match on the name.
//     This is what makes a single letter/word like "a" return every name
//     containing it. Backed by the trgm GIN index for patterns of 3+ chars.
//   - full_name % q                -> pg_trgm fuzzy match, catches typos
//     ("Jhon" -> "John") that ILIKE alone would miss.
//   - assigned_role::text ILIKE '%q%' -> substring match against the role
//     enum (SuperAdmin, Manager, Developer, Marketing, CustomStaff, HR),
//     cast to text since ILIKE can't operate on an enum directly. This is
//     what lets q=Developer or q=dev return everyone in that role.
//
// similarity() (computed against full_name only) ranks name matches best
// match first; pure role matches still come back, just ordered after the
// closer name matches since their similarity score will be 0/low.
// ---------------------------------------------------------------------------
export const searchEmployeesService = async (q: string) => {
  return prisma.$queryRaw<EmployeeSearchRow[]>`
    SELECT
      employee_id AS "employeeId",
      full_name AS "fullName",
      email_address AS "emailAddress",
      assigned_role AS "assignedRole",
      assigned_department AS "assignedDepartment",
      appraisal_state AS "appraisalState",
      base_salary AS "baseSalary",
      allowances,
      deductions,
      is_active AS "isActive",
      joined_at AS "joinedAt",
      username,
      team_id AS "teamId",
      manager_id AS "managerId",
      similarity(full_name, ${q}) AS similarity
    FROM employees
    WHERE full_name ILIKE '%' || ${q} || '%'
       OR full_name % ${q}
       OR assigned_role::text ILIKE '%' || ${q} || '%'
    ORDER BY similarity DESC, full_name ASC
    LIMIT 20;
  `;
};

export const getEmployeeByIdService = async (id: bigint) => {
  return prisma.employee.findUnique({
    where: {
      employeeId: id,
    },
    select: {
      employeeId: true,
      fullName: true,
      emailAddress: true,
      assignedRole: true,
      assignedDepartment: true,
      appraisalState: true,
      baseSalary: true,
      allowances: true,
      deductions: true,
      isActive: true,
      joinedAt: true,
      username: true,
      last_login: true,
      teamId: true,
      managerId: true,
    }
  });
};

export const updateEmployeeService = async (
  id: bigint,
  data: any
) => {
  return prisma.employee.update({
    where: {
      employeeId: id,
    },
    data,
  });
};

export const deleteEmployeeService = async (id: bigint) => {
  return prisma.employee.delete({
    where: {
      employeeId: id,
    },
  });
};